package conf

const (
	SUCCESS     = 200
	SUCCESS_MSG = "success"

	FAIL = 444
	//error
	ERROR_IMG_KIND_TYPE     = 3001
	ERROR_IMG_KIND_TYPE_MSG = "图片类型错误"

	ERROR_PHONE_IS_EXIST     = 3002
	ERROR_PHONE_IS_EXIST_MSG = "手机号已经注册"

	ERROR_NICKNAME_EXIST     = 3003
	ERROR_NICKNAME_EXIST_MSG = "昵称已经使用"

	ERROR_ACCOUNT_NOT_EXIST_OR_PASS_ERROR     = 3004
	ERROR_ACCOUNT_NOT_EXIST_OR_PASS_ERROR_MSG = "手机号或密码错误"
)
